# Remember playback position
save-position-on-quit=yes
watch-later-options=start

# Remember volume
volume-restore-data=volume

# Default volume (only used if no previous value exists)
volume=50

# Better quality
profile=gpu-hq

# Enable hardware decoding
hwdec=auto-safe

# Keep window size
keep-open=no

# Cache
cache=yes

# Subtitle settings
sub-auto=fuzzy
slang=en,bn

# Screenshot format
screenshot-format=png
